### ISSUE TITLE
Doesn't update.

### ISSUE THREAD

**Issue by Sikatsu** [PlaceholderAPI/Essentials-Expansion#1]
I tried to update the essentials expansion in-game:

16.03 12:28:50 [Server] INFO Sikatsu issued server command: /papi ecloud download Essentials
16.03 12:28:50 [Server] INFO Attempting download of expansion: Essentials by user: Sikatsu from url: http://api.extendedclip.com/media/PAPI-Expansion-Essentials_KbbY4QK.jar
16.03 12:28:51 [Server] INFO Download of expansion: Essentials complete!
16.03 12:28:54 [Server] INFO Sikatsu issued server command: /papi ecloud reload

Yet after the reload it still says there are updates.

**Comment by extendedclip** [comment]
Odd. What version shows when you do /papi info essentials

**Comment by Sikatsu** [comment]
1.1.2, which should be the latest. But in /papi ecloud list all it says theres an update since it's gold.
