### ISSUE TITLE
Placeholder Request to show co-ordinates of nearest player

### ISSUE THREAD

**Issue by axemwa** [PlaceholderAPI/Essentials-Expansion#10]
Another suggestion if possible to add Essentials Placeholders showing the x y and z co-ordinates of the nearest player is, with the radius being set to what ever it is set by default in the config by the server owner
Something like this?

%essentials.near_x%
%essentials.near_y%
%essentials.near_z%

The /near command in essentials only shows the players name and radius but not the coordinatess, would you still be able to find a way to make this work by making the placeholder track the nearest players location somehow, or would I first have to make a feature request to essentials and ask them to make a feature for that first so you can hook into it (if that's the correct term)?

**Comment by axemwa** [comment]
or a player placeholder where you can set the radius within the placeholder itself
eg:

%player_near_#(radius set in placeholder)_x%
%player_near_#(radius set in placeholder)_y%
%player_near_#(radius set in placeholder)_z%

**Comment by BlitzOffline** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/placeholders#parsenear
