### ISSUE TITLE
Offline Essentials Placeholder Support

### ISSUE THREAD

**Issue by Midnight9746** [PlaceholderAPI/Essentials-Expansion#15]
Requested Feature:
- Allowing offline support for essentials rank/nicknames (and Placeholders in general). I joined the Discord server asking for help and they had me use parseother but the thing was that it didn't show the offline player, only an empty space where the text would go. Only their username displayed. I would like "(Rank) Player" to show up instead.

**Comment by aBo0oDyy** [comment]
Hey there,
I've just added support for offline players for all placeholders (expect `%essentials_has_kit_KIT%` and `%essentials_worth%`, they require online player).
Can you please test it for me? if it's working fine, I'll update it in the eCloud.

Download it from [here](https://aboodyy.net/PAPI-Expansion-Essentials.jar) and replace it with the older one in `plugins/PlaceholderAPI/expansions`.

**Comment by Midnight9746** [comment]
@aBooDyy Terribly sorry... didn't noticed you responded.. let alone the fact that I forgot this was something I posted about. If it's not already updated... yes the placeholders work for offline players.

Thank you.

**Comment by aBooDyy** [comment]
No worries, thanks for letting me know.
I'll see if I'll just merge the PR myself and update it in the [eCloud](https://api.extendedclip.com/all/) later.

**Comment by Starmism** [comment]
Added in 1.4.0
