### ISSUE TITLE
Kit cooldown timer

### ISSUE THREAD

**Issue by Sikatsu** [PlaceholderAPI/Essentials-Expansion#2]
For some reason if you do not have access to the kit or if you just collected the kit it shows a wrong cooldown. (24 days+ while it should be 3 days)

**Comment by Sikatsu** [comment]
Closed, but was it fixed?

**Comment by darbyjack** [comment]
Months ago. I believe it was you in the Discord I gave the copy to check and you okayed it. If it wasn't you, it was someone else.
