### ISSUE TITLE
Request - Remaining jail time placeholder

### ISSUE THREAD

**Issue by Bbro122** [PlaceholderAPI/Essentials-Expansion#25]
There is a placeholder for if the player is jailed however there is no placeholder for how long the player is jailed

**Comment by Starmism** [comment]
Hey! I just got around to doing this, here's a build of the expansion with %essentials_jailed_time_remaining%. It requires EssentialsX dev builds, version 2.19.0 or higher. Once the dev builds become stable, I'll PR this into the main expansion.

[HelpChat Discord Link](https://helpch.at/discord)
[Discord File Link](https://discord.com/channels/164280494874165248/573429521554866178/860838238381539358)
