### ISSUE TITLE
Players Online count not working

### ISSUE THREAD

**Issue by D3adhkwen** [PlaceholderAPI/Essentials-Expansion#26]
Issue
What is the issue? Describe it like you would tell a friend.

Online player count is always showing (/60). %essentials_safe_online% placeholder is not working.

Expected behaviour
What should PlaceholderAPI do?

Show the correct playercount excluding vanished player (since the placeholder is meant to do that)

Actual behaviour
What does PlaceholderAPI actually do?

It doesn't show anything.

How to reproduce
What steps did you made, to get this bug?

PlaceholderAPI 2.10.9
EssentialsX 2.18.1.0
TAB 2.8.4

Console show the error:

[Fri, 28. Aug 2020 17:45:16 SGT INFO] [TAB] Expansion essetials is used but not installed. Installing!
[Fri, 28. Aug 2020 17:45:16 SGT INFO] Failed to find an expansion named: essetials

^ (seems like it is a typo in development?)

Included below is the PlaceholderAPI error report.
[PlaceholderAPI.errors.txt](https://github.com/PlaceholderAPI/Essentials-Expansion/files/5143262/PlaceholderAPI.errors.txt)

**Comment by Lusteroth** [comment]
It's fixed in latest dev build of EssentialsX
