### ISSUE TITLE
In-game calendar

### ISSUE THREAD

**Issue by Diablolend** [PlaceholderAPI/Essentials-Expansion#28]
Hi. I previously used the {WORLDTIME24} | {WORLDDATE} parameters in Essentials Motd to track the in-game calendar. But now I want to implement this using PlaceholderAPI. However, I have not seen anything like this anywhere in Placeholders. Perhaps this is a feature of Essentials? If yes, can it be implemented?

**Comment by Diablolend** [comment]
Example:
https://i.imgur.com/CcJd3nI.png

**Comment by Diablolend** [comment]
@darbyjack , check this please.

**Comment by Andre601** [comment]
Don't tag people and wait patiently.
Tagging others halfhazardly only gets you ignored.

**Comment by Diablolend** [comment]
I'm sorry, but I throught nothing happened here for three months. That's why I tagged. 🤔

**Comment by Starmism** [comment]
Added in 1.4.0!
