### ISSUE TITLE
Essentials Home Placeholder %essentials_home_max% displays minimum 1

### ISSUE THREAD

**Issue by JustJP2K** [PlaceholderAPI/Essentials-Expansion#30]
if you use %essentials_homes_set%/%essentials_homes_max%
To display the amount of homes you have set vs the amount you have it will always display 0/1 even if you have 0 homes.

example:
sethome.multiple.default:
default: 0
sethome.multiple.extra:
extra: 2

then it display for the default one 0/1 which is incorrect, it should say 0/0
it displays it correctly for extra 0/2.

**Comment by Starmism** [comment]
This is a bug in EssentialsX. The check starts with 1, and only checks the default multiple value if the player has the permission `essentials.sethome.multiple`.
