### ISSUE TITLE
New Placeholder Suggestion - specific item worth placeholder

### ISSUE THREAD

**Issue by Jupitour** [PlaceholderAPI/Essentials-Expansion#31]
Just suggesting a new placeholder that would allow you to show the essentials worth of specific items.

The only currently available option is **%essentials_worth%**, which shows the worth of the item the player is holding. The suggestion is for something like **%essentials_worth_<item name>%** so that it can be displayed in shops.

**Comment by Funny-cube** [comment]
Added in #32
