### ISSUE TITLE
[Suggestion] New Placeholder - Private Message Toggle

### ISSUE THREAD

**Issue by RinNiko** [PlaceholderAPI/Essentials-Expansion#35]
I just want to suggest for new placeholder for /msg toggle in essentails.

Example: %essentials_pm_toggle%

Return: yes or no

**Comment by iGabyTM** [comment]
This already exists, it is called `%essentials_msg_ignore%`.

**Comment by RinNiko** [comment]
![image](https://user-images.githubusercontent.com/49575027/135717833-28b974c7-818f-414e-9805-03e2f8027e8e.png)
Yeah but don't know why it not work ?
