### ISSUE TITLE
`%essentials_home_<number>%` any homes above 10 dont show

### ISSUE THREAD

**Issue by Kosett15** [PlaceholderAPI/Essentials-Expansion#38]
Hello any homes above 10 for this placeholder do not show up and show this.
![2021-12-29_14 28 31](https://user-images.githubusercontent.com/96830996/147674415-5e56a61e-14bb-4cd7-94d6-3cd8bca3ca19.png)
s

**Comment by darbyjack** [comment]
Can you let me know if this fixes it? [PAPI-Expansion-Essentials.zip](https://github.com/PlaceholderAPI/Essentials-Expansion/files/7831764/PAPI-Expansion-Essentials.zip)

**Comment by NekrosBurek** [comment]
@darbyjack i would like to confirm that the downloaded PAPI expansion works over 10 homes
