### ISSUE TITLE
Issues while trying to round the location numbers

### ISSUE THREAD

**Issue by NekrosBurek** [PlaceholderAPI/Essentials-Expansion#43]
When trying to round numbers with math extension i get errors in console 

`[09:01:30 WARN]: [PlaceholderAPI] [Math] Invalid Placeholder detected!`
`[09:01:30 WARN]: [PlaceholderAPI] [Math] Placeholder: %math_:half-up_{essentials_home_1_x}%`
`[09:01:30 WARN]: [PlaceholderAPI] [Math] '227.2476827494362.5' is not a valid Math Expression.`

for some reason values X and Z are returning values with double decimal points like -5.87897896.5

**Comment by Andre601** [comment]
> `%math_:half-up_{essentials_home_1_x}%`

This isn't how you should use the math expansion. It's for math expressions and not just to round stuff.
