### ISSUE TITLE
Bug and suggestion %essentials_home.....

### ISSUE THREAD

**Issue by Rawxdealz** [PlaceholderAPI/Essentials-Expansion#51]
Suggestion:
For homes: essentialsX has these placeholders: 

%essentials_home_<number>%
%essentials_home_<number>_<x|y|z>%

Can %essentials_home_<number>_world% be added aswel?

Bug: 
%essentials_home_<number>_<x|y|z>% sometimes show numbers with 10 digits. Can it be made it only show 1 number after the . ?
There is also an .5 extra after each coordinates. 

See picture for the bug and suggestion:
![image](https://user-images.githubusercontent.com/42896942/164991523-119be791-f89d-4f04-8aa3-5107c0d97b07.png)

**Comment by Andre601** [comment]
Did you actually update the expansion?
The `.5` thing gives me the idea that you didn't, since it was an issue that got fixed recently...

**Comment by Rawxdealz** [comment]
The 0.5 is fixed after updating but the suggestion i made not, and the
other bug is still there

I tried to answer on gitbuh but i cant find it anymore


Op ma 25 apr. 2022 om 00:27 schreef Andre_601 ***@***.***>:

**Comment by Rawxdealz** [comment]
Ah, found it again. Updating fixed the 0.5 error yes. Thank you for that.
The 10+ digit coordinates bug is still there.
And the suggestion for home worlds is still pending i guess.

**Comment by Rawxdealz** [comment]
![image](https://user-images.githubusercontent.com/42896942/165159344-66aaa376-5839-4bdc-9c1a-dfc063f1477b.png)
updated image
