### ISSUE TITLE
essentials placeholder

### ISSUE THREAD

**Issue by Aadi-mone** [PlaceholderAPI/Essentials-Expansion#53]
![image](https://user-images.githubusercontent.com/87631878/178298535-572eb075-41a6-4904-8a95-df02f39acabd.png)

look at the scoreboard, I use the jail placeholder, and when the jail time ends it shows **"52 years 5 months 27days**" how do I change that?

**Comment by iGabyTM** [comment]
@Aadi-mone can you try this version https://cdn.discordapp.com/attachments/919994546987880488/1025876443579818054/PAPI-Expansion-Essentials.jar ?

**Comment by Aadi-mone** [comment]
should I download this to the expansions folder?

**Comment by iGabyTM** [comment]
yes, replace the existing expansion jar with this and try the placeholder @Aadi-mone

**Comment by Aadi-mone** [comment]
oh, I guess it's solved:

![2022-10-05_11 52 01](https://user-images.githubusercontent.com/87631878/193994915-c6c0319a-58d4-4a79-819f-5251d3478b0d.png)
