### ISSUE TITLE
EssentialsX Expansion

### ISSUE THREAD

**Issue by zikehalil3535** [PlaceholderAPI/Essentials-Expansion#60]
EssentialsX Placeholderapi expansion baltop placeholders only uptaded If I do /papi reload What can I do for reload itself? Normally automatic update is required. 

"Enable this to also log all transactions from other plugins through Vault.
This can cause the economy log to fill up quickly so should only be enabled for testing purposes!
economy-log-update-enabled: true"

The only setting I can find remotely related is this one - I enabled it and restarted and the results were still the same.  The placeholder was not updating when I change my balance.
I think it may be something with the placeholderapi.  Because everything updates fine in the essentials /baltop and essentials /bal - but the displays in the menu with essentials baltop placeholder do not.

**Comment by zikehalil3535** [comment]
Any updates?

**Comment by cj89898** [comment]
This came up in the [HelpChat Discord](https://helpch.at/discord) the other day. We came to a conclusion that automatically updating the baltop is something that shouldn't be left to a PAPI expansion to handle.

Normally the baltop updates when a user runs a `/baltop` command, with a time limit.

In the discord I suggested using a CommandScheduler plugin to schedule a `/baltop force` command to be run every x minutes.

**Comment by zikehalil3535** [comment]
> This came up in the [HelpChat Discord](https://helpch.at/discord) the other day. We came to a conclusion that automatically updating the baltop is something that shouldn't be left to a PAPI expansion to handle.
> 
> Reason being it can't be done every time a placeholder is requested, as the calculations would be way too much to handle since placeholders could be called multiple times per second and thousands of users need to be calculated. It would need a custom scheduler.
> 
> Normally the baltop updates when a user runs a `/baltop` command, with a time limit.
> 
> In the discord I suggested using a CommandScheduler plugin to schedule a `/baltop force` command to be run every x minutes.

I tried before Baltop force not working. Look this example
![image](https://user-images.githubusercontent.com/88826436/228228209-01b50f0d-6eba-45ba-91ac-1f0bc3f59fbb.png)

**Comment by zikehalil3535** [comment]
/papi parse Whiskey %essentials_baltop_player_1% - HalilTest
/papi parse Whiskey %essentials_baltop_balance_formatted_1% - 10
