### ISSUE TITLE
Fix maven building so ci builds don't fail

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/Essentials-Expansion#7]
I'm not sure where the issue is yet because I haven't had a chance to look into it but after switching to the Ender Zone repo for Essentials X it seems we are having issues with building the expansion in Jenkins. Just posting this issue so I don't forget....

**Comment by Mishyy** [comment]
What exactly is the issue senor clip.

**Comment by extendedclip** [comment]
Glare added some placeholders to the expansion and changed the essentials repo  to the official instead of  mine today. He said everything builds fine locally but on Jenkins the build failed with this error. https://paste.glaremasters.me/uvomejeyid.sql
